=== hepl-xml/xsd/ex05 namespaces/book3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://khi.be/ns/book">
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="isbn">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="\d{9}[\dX]"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="title" type="xs:token"/>
				<xs:element name="author">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firstname" type="xs:token"/>
							<xs:element name="lastname" type="xs:token"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publisher" type="xs:token"/>
				<xs:element name="edition" type="xs:positiveInteger"/>
			</xs:sequence>
			<xs:attribute name="added_at" type="xs:dateTime"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hepl-xml/xsd/ex05 namespaces/book4_not_ok.xml
<?xml version="1.0" encoding="UTF-8"?>
<book
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://khi.be/ns/book book3.xsd"
	xmlns="http://khi.be/ns/book"
	added_at="2011-07-15T15:02:00">
	<isbn>0596001975</isbn>
	<title>Java &amp; XML</title>
	<author>
		<firstname>Brett</firstname>
		<lastname>McLaughlin</lastname>
	</author>
	<publisher>O'Reilly</publisher>
	<edition>2</edition>
</book>
