=== hepl-xml/xsd/ex03 complex types/books2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="person">
		<xs:sequence>
			<xs:element name="name" type="xs:token"/>
			<xs:element name="born" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="author">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="person">
					<xs:sequence>
						<xs:element name="dead" type="xs:integer" minOccurs="0"/>
						<xs:element name="published" type="xs:integer"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="books">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="book" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="title" type="xs:token"/>
							<xs:element ref="author" minOccurs="0"
								maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hepl-xml/xsd/ex03 complex types/books2.xml
<?xml version="1.0" encoding="UTF-8"?>
<books
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="books2.xsd">
	<book>
		<title>Germinal</title>
		<author>
			<name>Emile Zola</name>
			<born>1840</born>
			<dead>1902</dead>
			<published>40</published>
		</author>
	</book>
	<book>
		<title>Vis et n'oublie pas</title>
		<author>
			<name>Valentin Raspoutine</name>
			<born>1937</born>
			<published>12</published>
		</author>
	</book>
</books>
